/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jmbleopamvvsmoizhmhz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptYmxlb3BhbXZ2c21vaXpobWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjQ0NjQsImV4cCI6MjA3MzEwMDQ2NH0.Jy-hcPt8OTtXDcvRo0ktxGW91yKPkTbf-ECV9e33E-I"