import { useState } from 'react';
import { Card } from './ui/card';
import { Button } from './ui/button';
import { Share2, Download, Copy, MapPin, Clock, DollarSign } from 'lucide-react';
import { toast } from 'sonner';
import type { OptimizedRoute } from '../App';

interface RouteExportProps {
  route: OptimizedRoute;
  allRoutes: OptimizedRoute[];
}

export function RouteExport({ route, allRoutes }: RouteExportProps) {
  const [isExporting, setIsExporting] = useState(false);

  const generateRouteText = () => {
    const routeText = `
🗺️ GaavConnect AI Optimized Route
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📍 Route Details:
• Algorithm: ${route.algorithm.toUpperCase()}
• Total Distance: ${route.totalDistance}
• Duration: ${route.totalDuration}
• Estimated Cost: ₹${route.totalCost}

🚩 Destinations (${route.stops.length} stops):
${route.stops.map((stop, index) => `${index + 1}. ${stop.name}`).join('\n')}

🛣️ Route Segments:
${route.segments.map((segment, index) => 
  `${index + 1}. ${segment.from} → ${segment.to}
   📏 ${segment.distance} | ⏱️ ${segment.duration} | 💰 ₹${segment.cost}`
).join('\n\n')}

🤖 AI Optimization Summary:
• Compared ${allRoutes.length} different route algorithms
• Best algorithm: ${route.algorithm}
• Real-time GPS data used for accurate calculations
• Enhanced TSP Genetic Algorithm optimization

Generated by GaavConnect - AI Route Optimization
🌐 Powered by real-time data & genetic algorithms
    `.trim();

    return routeText;
  };

  const copyToClipboard = async () => {
    try {
      const routeText = generateRouteText();
      await navigator.clipboard.writeText(routeText);
      toast.success('Route copied to clipboard!');
    } catch (error) {
      console.error('Failed to copy:', error);
      toast.error('Failed to copy route');
    }
  };

  const shareRoute = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'GaavConnect AI Optimized Route',
          text: generateRouteText(),
        });
      } catch (error) {
        console.error('Failed to share:', error);
        copyToClipboard(); // Fallback to copy
      }
    } else {
      copyToClipboard(); // Fallback for browsers without Web Share API
    }
  };

  const downloadRoute = () => {
    setIsExporting(true);
    try {
      const routeText = generateRouteText();
      const blob = new Blob([routeText], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `gaavconnect-route-${Date.now()}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      toast.success('Route downloaded successfully!');
    } catch (error) {
      console.error('Failed to download:', error);
      toast.error('Failed to download route');
    } finally {
      setIsExporting(false);
    }
  };

  const generateGoogleMapsUrl = () => {
    if (route.stops.length === 0) return '';
    
    const origin = route.segments[0]?.from || '';
    const destination = route.stops[route.stops.length - 1]?.name || '';
    const waypoints = route.stops.slice(0, -1).map(stop => stop.name).join('|');
    
    const baseUrl = 'https://www.google.com/maps/dir/';
    const params = new URLSearchParams({
      api: '1',
      origin: origin,
      destination: destination,
      waypoints: waypoints,
      travelmode: 'driving'
    });
    
    return `${baseUrl}?${params.toString()}`;
  };

  const openInGoogleMaps = () => {
    const url = generateGoogleMapsUrl();
    if (url) {
      window.open(url, '_blank');
    } else {
      toast.error('Unable to generate Google Maps link');
    }
  };

  return (
    <Card className="p-6 border-[#E6E6FA] shadow-lg">
      <div className="flex items-center gap-2 mb-4">
        <Share2 className="w-5 h-5 text-[#6A0DAD]" />
        <h3 className="text-lg font-semibold text-[#6A0DAD]">Export & Share Route</h3>
      </div>

      {/* Route Summary */}
      <div className="bg-gradient-to-r from-purple-50 to-blue-50 p-4 rounded-lg mb-4">
        <div className="grid grid-cols-3 gap-4 text-center">
          <div className="flex flex-col items-center">
            <MapPin className="w-5 h-5 text-[#6A0DAD] mb-1" />
            <span className="text-sm font-medium text-gray-700">{route.totalDistance}</span>
            <span className="text-xs text-gray-500">Distance</span>
          </div>
          <div className="flex flex-col items-center">
            <Clock className="w-5 h-5 text-[#6A0DAD] mb-1" />
            <span className="text-sm font-medium text-gray-700">{route.totalDuration}</span>
            <span className="text-xs text-gray-500">Duration</span>
          </div>
          <div className="flex flex-col items-center">
            <DollarSign className="w-5 h-5 text-[#6A0DAD] mb-1" />
            <span className="text-sm font-medium text-gray-700">₹{route.totalCost}</span>
            <span className="text-xs text-gray-500">Cost</span>
          </div>
        </div>
      </div>

      {/* Export Actions */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <Button
          onClick={shareRoute}
          variant="outline"
          className="flex items-center gap-2 text-sm"
        >
          <Share2 className="w-4 h-4" />
          Share
        </Button>
        
        <Button
          onClick={copyToClipboard}
          variant="outline"
          className="flex items-center gap-2 text-sm"
        >
          <Copy className="w-4 h-4" />
          Copy
        </Button>
        
        <Button
          onClick={downloadRoute}
          disabled={isExporting}
          variant="outline"
          className="flex items-center gap-2 text-sm"
        >
          <Download className="w-4 h-4" />
          {isExporting ? 'Saving...' : 'Download'}
        </Button>
        
        <Button
          onClick={openInGoogleMaps}
          className="flex items-center gap-2 text-sm bg-[#6A0DAD] hover:bg-[#8B2DC2] text-white"
        >
          🗺️ Maps
        </Button>
      </div>

      <p className="text-xs text-gray-500 mt-3 text-center">
        Share your AI-optimized route with friends or save for later use
      </p>
    </Card>
  );
}
